# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_class', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lektor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lektor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('przynaleznosc_grupy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='prowadzacy_lektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Lektor'),
        ),
        migrations.AddField(
            model_name='classdate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Student'),
        ),
    ]
