# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('score', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Student')),
            ],
        ),
        migrations.AddField(
            model_name='classdate',
            name='subject',
            field=models.CharField(default=b'testowy temat', max_length=200),
        ),
    ]
