# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0002_auto_20161024_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='date',
        ),
        migrations.AddField(
            model_name='grades',
            name='date_of_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 26, 8, 35, 36, 483000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
