# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0002_auto_20170415_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdate',
            name='has_homework',
            field=models.ManyToManyField(related_name='has_homework', to='edziennik.Student'),
        ),
        migrations.AlterField(
            model_name='classdate',
            name='student',
            field=models.ManyToManyField(related_name='student', to='edziennik.Student'),
        ),
    ]
