# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0003_auto_20161026_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='date_of_test',
            field=models.DateField(blank=True, null=True),
        ),
    ]
