# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0003_auto_20170907_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizlet',
            field=models.BooleanField(default=False),
        ),
    ]
