# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0004_student_quizlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdate',
            name='lector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edziennik.Lector'),
        ),
    ]
