# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edziennik', '0004_auto_20161028_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rodzic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
