# Generated by Django 2.1.4 on 2018-12-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizlet_username', models.CharField(blank=True, max_length=30)),
                ('quizlet_password', models.CharField(blank=True, max_length=30)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=30)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=30)),
                ('sms_when_absent', models.BooleanField()),
                ('sms_when_no_homework', models.BooleanField()),
                ('sms_message_absence', models.CharField(blank=True, max_length=300)),
                ('sms_message_no_homework', models.CharField(blank=True, max_length=400)),
                ('school_admin_email', models.BooleanField()),
                ('send_email_weekly_attendance_report', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='quizlet_username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='classdate',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Lector'),
        ),
        migrations.AlterField(
            model_name='classdate',
            name='subject',
            field=models.CharField(default='testowy temat', max_length=200),
        ),
        migrations.AlterField(
            model_name='lector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sms',
            name='checked_once',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sms',
            name='checked_twice',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sms',
            name='delivered',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sms',
            name='service',
            field=models.CharField(choices=[('smsapipl', 'smsapipl'), ('twilio', 'twilio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='admin_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edziennik.Lector'),
        ),
    ]
